version: '3.7'
services:
  go-server:
    container_name: go-server
    build:
      context: ./go-server
      dockerfile: Dockerfile
    image: service1
    env_file:
      - go-server/.env
    ports:
      - "8081:8080"
    restart: on-failure
    networks:
      - application

  python-server:
    container_name: python-server
    build:
      context: ./python-server
      dockerfile: Dockerfile
    image: python-server
    env_file:
      - python-server/.env
    ports:
      - "8082:8080"
    restart: on-failure
    networks:
      - application

  node-server:
    container_name: node-server
    build:
      context: ./node-server
      dockerfile: Dockerfile
    image: node-server
    env_file:
      - node-server/.env
    ports:
      - "8083:8080"
    restart: on-failure
    networks:
      - application


# Networks to be created to facilitate communication between containers
networks:
  application:
    driver: bridge