version: '3.7'
services:
  go-server:
    container_name: go-server
    build:
      context: ./go-server
      dockerfile: Dockerfile
    image: service1
    env_file:
      - go-server/.env
    ports:
      - "8081:8080"
    restart: on-failure
    networks:
      - application

# Networks to be created to facilitate communication between containers
networks:
  application:
    driver: bridge