apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  labels:
    app: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: node-server:latest #todo: good name
        imagePullPolicy: IfNotPresent
        resources:
          limits:
                  memory: "128Mi"
                  cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-server
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30953
    port: 8080
  selector:
    app: node-server